// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolBill.Data;

#nullable disable

namespace SchoolBill.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241214071955_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolBill.Models.BillDetail", b =>
                {
                    b.Property<int>("Detailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Detailid"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Billid")
                        .HasColumnType("integer");

                    b.Property<string>("Particulars")
                        .HasColumnType("text");

                    b.HasKey("Detailid");

                    b.HasIndex("Billid");

                    b.ToTable("BillDetails");
                });

            modelBuilder.Entity("SchoolBill.Models.BillMaster", b =>
                {
                    b.Property<int>("Billid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Billid"));

                    b.Property<int>("AppNo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer");

                    b.HasKey("Billid");

                    b.ToTable("BillMasters");
                });

            modelBuilder.Entity("SchoolBill.Models.ClassEntity", b =>
                {
                    b.Property<int>("Classid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Classid"));

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.HasKey("Classid");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolBill.Models.SchoolEntity", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchoolId"));

                    b.Property<int>("Billid")
                        .HasColumnType("integer");

                    b.Property<string>("Phoneno")
                        .HasColumnType("text");

                    b.Property<string>("SchoolAddress")
                        .HasColumnType("text");

                    b.Property<string>("SchoolEmail")
                        .HasColumnType("text");

                    b.Property<string>("SchoolName")
                        .HasColumnType("text");

                    b.HasKey("SchoolId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("SchoolBill.Models.SectionEntity", b =>
                {
                    b.Property<int>("Sectionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sectionid"));

                    b.Property<int?>("ClassEntityClassid")
                        .HasColumnType("integer");

                    b.Property<int>("Classid")
                        .HasColumnType("integer");

                    b.Property<string>("Sectionname")
                        .HasColumnType("text");

                    b.HasKey("Sectionid");

                    b.HasIndex("ClassEntityClassid");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("SchoolBill.Models.StudentEntity", b =>
                {
                    b.Property<int>("Studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Studentid"));

                    b.Property<int>("Billid")
                        .HasColumnType("integer");

                    b.Property<int>("Classid")
                        .HasColumnType("integer");

                    b.Property<string>("ParentName")
                        .HasColumnType("text");

                    b.Property<int>("Sectionid")
                        .HasColumnType("integer");

                    b.Property<string>("StuContactno")
                        .HasColumnType("text");

                    b.Property<string>("Studentname")
                        .HasColumnType("text");

                    b.HasKey("Studentid");

                    b.HasIndex("Billid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolBill.Models.BillDetail", b =>
                {
                    b.HasOne("SchoolBill.Models.BillMaster", null)
                        .WithMany("BillDetails")
                        .HasForeignKey("Billid");
                });

            modelBuilder.Entity("SchoolBill.Models.SectionEntity", b =>
                {
                    b.HasOne("SchoolBill.Models.ClassEntity", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassEntityClassid");
                });

            modelBuilder.Entity("SchoolBill.Models.StudentEntity", b =>
                {
                    b.HasOne("SchoolBill.Models.BillMaster", null)
                        .WithMany("Students")
                        .HasForeignKey("Billid");
                });

            modelBuilder.Entity("SchoolBill.Models.BillMaster", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolBill.Models.ClassEntity", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
